"""FOCAL baseline: Deterministic encoder with deep metric learning loss.

Key differences from PEARL:
- No information bottleneck / product-of-Gaussians
- Mean aggregation of context embeddings
- Eq. 13 loss: same-task pairs minimize squared embedding distance, while
  different-task pairs use an inverse-power distance penalty

Online setting (data collection enabled) is intentional because the paper's
datasets are not available in this benchmark. The Eq. 13 contrastive loss is
implemented in this harness.
"""

OPS = [
    {
        "op": "replace",
        "file": "oyster/custom_meta_rl.py",
        "start_line": 357,
        "end_line": 494,
        "content": (
            "# =====================================================================\n"
            "# EDITABLE — Custom imports\n"
            "# =====================================================================\n"
            "\n"
            "\n"
            "# =====================================================================\n"
            "# EDITABLE — Custom Meta-RL Agent\n"
            "# =====================================================================\n"
            "class CustomMetaRLAgent(nn.Module):\n"
            "    \"\"\"FOCAL agent: deterministic encoder with mean aggregation.\"\"\"\n"
            "\n"
            "    def __init__(self, obs_dim, action_dim, latent_dim=5, net_size=300,\n"
            "                 reward_dim=1, use_next_obs_in_context=False, **kwargs):\n"
            "        super().__init__()\n"
            "        self.obs_dim = obs_dim\n"
            "        self.action_dim = action_dim\n"
            "        self.latent_dim = latent_dim\n"
            "        self.use_next_obs_in_context = use_next_obs_in_context\n"
            "        self.sparse_rewards = kwargs.get('sparse_rewards', False)\n"
            "\n"
            "        context_input_dim = obs_dim + action_dim + reward_dim\n"
            "        if use_next_obs_in_context:\n"
            "            context_input_dim += obs_dim\n"
            "\n"
            "        # Deterministic encoder: output is latent_dim (no IB)\n"
            "        self.context_encoder = build_mlp(\n"
            "            context_input_dim, latent_dim,\n"
            "            hidden_dim=200, n_layers=3,\n"
            "        )\n"
            "\n"
            "        # Policy, Q-functions, V-function (z-conditioned)\n"
            "        self.policy = build_policy(obs_dim, action_dim, latent_dim, net_size)\n"
            "        self.qf1 = build_qf(obs_dim, action_dim, latent_dim, net_size)\n"
            "        self.qf2 = build_qf(obs_dim, action_dim, latent_dim, net_size)\n"
            "        self.vf = build_vf(obs_dim, latent_dim, net_size)\n"
            "        self.target_vf = copy.deepcopy(self.vf)\n"
            "\n"
            "        self.register_buffer('z', torch.zeros(1, latent_dim))\n"
            "        self._context = None\n"
            "\n"
            "    def clear_context(self, num_tasks=1):\n"
            "        self.z = ptu.zeros(num_tasks, self.latent_dim)\n"
            "        self._context = None\n"
            "\n"
            "    def clear_z(self, num_tasks=1):\n"
            "        self.clear_context(num_tasks)\n"
            "\n"
            "    def sample_z(self):\n"
            "        pass  # z is deterministic\n"
            "\n"
            "    @property\n"
            "    def context(self):\n"
            "        return self._context\n"
            "\n"
            "    def update_context(self, inputs):\n"
            "        o, a, r, no, d, info = inputs\n"
            "        if self.sparse_rewards:\n"
            "            r = info.get('sparse_reward', r)\n"
            "        o = ptu.from_numpy(o[None, None, ...])\n"
            "        a = ptu.from_numpy(a[None, None, ...])\n"
            "        r = ptu.from_numpy(np.array([r])[None, None, ...])\n"
            "        no = ptu.from_numpy(no[None, None, ...])\n"
            "        if self.use_next_obs_in_context:\n"
            "            data = torch.cat([o, a, r, no], dim=2)\n"
            "        else:\n"
            "            data = torch.cat([o, a, r], dim=2)\n"
            "        if self._context is None:\n"
            "            self._context = data\n"
            "        else:\n"
            "            self._context = torch.cat([self._context, data], dim=1)\n"
            "\n"
            "    def infer_posterior(self, context):\n"
            "        \"\"\"Encode context and take mean over transitions.\"\"\"\n"
            "        embeddings = self.context_encoder(context)\n"
            "        # embeddings: (num_tasks, seq_len, latent_dim)\n"
            "        embeddings = embeddings.view(context.size(0), -1, self.latent_dim)\n"
            "        self.z = torch.mean(embeddings, dim=1)  # (num_tasks, latent_dim)\n"
            "\n"
            "    def adapt(self):\n"
            "        if self._context is not None:\n"
            "            self.infer_posterior(self._context)\n"
            "\n"
            "    def get_action(self, obs, deterministic=False):\n"
            "        z = self.z\n"
            "        obs_t = ptu.from_numpy(obs[None])\n"
            "        in_ = torch.cat([obs_t, z], dim=1)\n"
            "        return self.policy.get_action(in_, deterministic=deterministic)\n"
            "\n"
            "    def forward(self, obs, context):\n"
            "        self.infer_posterior(context)\n"
            "        task_z = self.z\n"
            "        t, b, _ = obs.size()\n"
            "        obs = obs.view(t * b, -1)\n"
            "        task_z = [z.repeat(b, 1) for z in task_z]\n"
            "        task_z = torch.cat(task_z, dim=0)\n"
            "        in_ = torch.cat([obs, task_z.detach()], dim=1)\n"
            "        policy_outputs = self.policy(\n"
            "            in_, reparameterize=True, return_log_prob=True)\n"
            "        return policy_outputs, task_z\n"
            "\n"
            "    def set_num_steps_total(self, n):\n"
            "        self.policy.set_num_steps_total(n)\n"
            "\n"
            "    def detach_z(self):\n"
            "        self.z = self.z.detach()\n"
            "\n"
            "    @property\n"
            "    def networks(self):\n"
            "        return [self.policy, self.qf1, self.qf2,\n"
            "                self.vf, self.target_vf]\n"
            "\n"
            "\n"
            "class CustomMetaRLAlgorithm:\n"
            "    \"\"\"FOCAL SAC with deep metric encoder loss.\"\"\"\n"
            "\n"
            "    def __init__(self, agent, env, train_tasks, eval_tasks,\n"
            "                 replay_buffer, enc_replay_buffer, config):\n"
            "        self.agent = agent\n"
            "        self.env = env\n"
            "        self.train_tasks = train_tasks\n"
            "        self.eval_tasks = eval_tasks\n"
            "        self.replay_buffer = replay_buffer\n"
            "        self.enc_replay_buffer = enc_replay_buffer\n"
            "        self.config = config\n"
            "\n"
            "        self.sampler = InPlacePathSampler(\n"
            "            env=env, policy=agent,\n"
            "            max_path_length=config['max_path_length'],\n"
            "        )\n"
            "\n"
            "        self.batch_size = config.get('batch_size', 256)\n"
            "        self.meta_batch = config.get('meta_batch', 16)\n"
            "        self.discount = config.get('discount', 0.99)\n"
            "        self.reward_scale = config.get('reward_scale', 5.0)\n"
            "        self.soft_target_tau = config.get('soft_target_tau', 0.005)\n"
            "        self.sparse_rewards = config.get('sparse_rewards', False)\n"
            "        self.use_next_obs_in_context = config.get('use_next_obs_in_context', False)\n"
            "        self.embedding_batch_size = config.get('embedding_batch_size', 64)\n"
            "        self.embedding_mini_batch_size = config.get('embedding_mini_batch_size', 64)\n"
            "        self.num_tasks_sample = config.get('num_tasks_sample', 5)\n"
            "        self.num_steps_prior = config.get('num_steps_prior', 400)\n"
            "        self.num_steps_posterior = config.get('num_steps_posterior', 0)\n"
            "        self.num_extra_rl_steps_posterior = config.get('num_extra_rl_steps_posterior', 400)\n"
            "        self.num_train_steps_per_itr = config.get('num_train_steps_per_itr', 2000)\n"
            "        self.update_post_train = config.get('update_post_train', 1)\n"
            "        self.contrastive_weight = 1.0\n"
            "        self.dml_beta = config.get('dml_beta', 1.0)\n"
            "        self.dml_epsilon = config.get('dml_epsilon', 1e-3)\n"
            "        self.dml_power = config.get('dml_power', 2.0)\n"
            "\n"
            "        lr = 3e-4\n"
            "        self.policy_optimizer = optim.Adam(agent.policy.parameters(), lr=lr)\n"
            "        self.qf1_optimizer = optim.Adam(agent.qf1.parameters(), lr=lr)\n"
            "        self.qf2_optimizer = optim.Adam(agent.qf2.parameters(), lr=lr)\n"
            "        self.vf_optimizer = optim.Adam(agent.vf.parameters(), lr=lr)\n"
            "        self.context_optimizer = optim.Adam(\n"
            "            agent.context_encoder.parameters(), lr=lr)\n"
            "\n"
            "    def collect_initial_data(self):\n"
            "        num_initial_steps = self.config.get('num_initial_steps', 200)\n"
            "        for idx in self.train_tasks:\n"
            "            self.env.reset_task(idx)\n"
            "            collect_data(\n"
            "                self.agent, self.env, self.sampler,\n"
            "                self.replay_buffer, self.enc_replay_buffer,\n"
            "                idx, num_initial_steps, 1, np.inf,\n"
            "                add_to_enc_buffer=True, config=self.config,\n"
            "            )\n"
            "\n"
            "    def train_iteration(self, iteration_idx):\n"
            "        for i in range(self.num_tasks_sample):\n"
            "            idx = np.random.randint(len(self.train_tasks))\n"
            "            self.env.reset_task(idx)\n"
            "            self.enc_replay_buffer.task_buffers[idx].clear()\n"
            "            if self.num_steps_prior > 0:\n"
            "                collect_data(\n"
            "                    self.agent, self.env, self.sampler,\n"
            "                    self.replay_buffer, self.enc_replay_buffer,\n"
            "                    idx, self.num_steps_prior, 1, np.inf,\n"
            "                    config=self.config,\n"
            "                )\n"
            "            if self.num_steps_posterior > 0:\n"
            "                collect_data(\n"
            "                    self.agent, self.env, self.sampler,\n"
            "                    self.replay_buffer, self.enc_replay_buffer,\n"
            "                    idx, self.num_steps_posterior, 1, self.update_post_train,\n"
            "                    config=self.config,\n"
            "                )\n"
            "            if self.num_extra_rl_steps_posterior > 0:\n"
            "                collect_data(\n"
            "                    self.agent, self.env, self.sampler,\n"
            "                    self.replay_buffer, self.enc_replay_buffer,\n"
            "                    idx, self.num_extra_rl_steps_posterior, 1,\n"
            "                    self.update_post_train,\n"
            "                    add_to_enc_buffer=False, config=self.config,\n"
            "                )\n"
            "\n"
            "        for _ in range(self.num_train_steps_per_itr):\n"
            "            indices = np.random.choice(\n"
            "                self.train_tasks, self.meta_batch)\n"
            "            self._take_step(indices)\n"
            "        return {}\n"
            "\n"
            "    def _take_step(self, indices):\n"
            "        mb_size = self.embedding_mini_batch_size\n"
            "        num_updates = self.embedding_batch_size // mb_size\n"
            "\n"
            "        context_batch = sample_context_from_buffer(\n"
            "            self.enc_replay_buffer, indices, self.embedding_batch_size,\n"
            "            sparse_rewards=self.sparse_rewards,\n"
            "            use_next_obs_in_context=self.use_next_obs_in_context,\n"
            "        )\n"
            "        self.agent.clear_z(num_tasks=len(indices))\n"
            "\n"
            "        for i in range(num_updates):\n"
            "            context = context_batch[:, i * mb_size: i * mb_size + mb_size, :]\n"
            "            self._update(indices, context)\n"
            "            self.agent.detach_z()\n"
            "\n"
            "    def _encode_task_context(self, context):\n"
            "        embeddings = self.agent.context_encoder(context)\n"
            "        embeddings = embeddings.view(context.size(0), -1, self.agent.latent_dim)\n"
            "        return torch.mean(embeddings, dim=1)\n"
            "\n"
            "    def _compute_contrastive_loss(self, indices, context):\n"
            "        \"\"\"FOCAL Eq. 13 deep metric learning loss.\"\"\"\n"
            "        half = context.size(1) // 2\n"
            "        labels_base = np.asarray(indices)\n"
            "        if labels_base.ndim == 0:\n"
            "            labels_base = labels_base[None]\n"
            "        if half == 0:\n"
            "            z = self._encode_task_context(context)\n"
            "            labels_np = labels_base\n"
            "        else:\n"
            "            ctx_a = context[:, :half, :]\n"
            "            ctx_b = context[:, half:2*half, :]\n"
            "            z = torch.cat([\n"
            "                self._encode_task_context(ctx_a),\n"
            "                self._encode_task_context(ctx_b),\n"
            "            ], dim=0)\n"
            "            labels_np = np.concatenate([labels_base, labels_base])\n"
            "\n"
            "        labels = torch.as_tensor(labels_np, device=context.device)\n"
            "        same_task = labels[:, None].eq(labels[None, :]).float()\n"
            "        dist_sq = torch.sum((z[:, None, :] - z[None, :, :]) ** 2, dim=-1)\n"
            "        positive_loss = same_task * dist_sq\n"
            "        dist = torch.sqrt(dist_sq + 1e-12)\n"
            "        negative_loss = (1.0 - same_task) * (\n"
            "            self.dml_beta /\n"
            "            (torch.pow(dist, self.dml_power) + self.dml_epsilon)\n"
            "        )\n"
            "        return (positive_loss + negative_loss).mean()\n"
            "\n"
            "    def _update(self, indices, context):\n"
            "        num_tasks = len(indices)\n"
            "        obs, actions, rewards, next_obs, terms = sample_sac_batch(\n"
            "            self.replay_buffer, indices, self.batch_size)\n"
            "\n"
            "        policy_outputs, task_z = self.agent(obs, context)\n"
            "        new_actions, policy_mean, policy_log_std, log_pi = policy_outputs[:4]\n"
            "\n"
            "        t, b, _ = obs.size()\n"
            "        obs_flat = obs.view(t * b, -1)\n"
            "        actions_flat = actions.view(t * b, -1)\n"
            "        next_obs_flat = next_obs.view(t * b, -1)\n"
            "\n"
            "        q1_pred = self.agent.qf1(obs_flat, actions_flat, task_z)\n"
            "        q2_pred = self.agent.qf2(obs_flat, actions_flat, task_z)\n"
            "        v_pred = self.agent.vf(obs_flat, task_z.detach())\n"
            "        with torch.no_grad():\n"
            "            target_v = self.agent.target_vf(next_obs_flat, task_z)\n"
            "\n"
            "        # Eq. 13 deep metric encoder loss\n"
            "        self.context_optimizer.zero_grad()\n"
            "        contrastive_loss = self._compute_contrastive_loss(indices, context)\n"
            "        encoder_loss = self.contrastive_weight * contrastive_loss\n"
            "        encoder_loss.backward(retain_graph=True)\n"
            "\n"
            "        # Q-function loss\n"
            "        self.qf1_optimizer.zero_grad()\n"
            "        self.qf2_optimizer.zero_grad()\n"
            "        rewards_flat = rewards.view(self.batch_size * num_tasks, -1)\n"
            "        rewards_flat = rewards_flat * self.reward_scale\n"
            "        terms_flat = terms.view(self.batch_size * num_tasks, -1)\n"
            "        q_target = rewards_flat + (1. - terms_flat) * self.discount * target_v\n"
            "        qf_loss = (torch.mean((q1_pred - q_target) ** 2) +\n"
            "                   torch.mean((q2_pred - q_target) ** 2))\n"
            "        qf_loss.backward()\n"
            "        self.qf1_optimizer.step()\n"
            "        self.qf2_optimizer.step()\n"
            "        self.context_optimizer.step()\n"
            "\n"
            "        # V-function loss\n"
            "        min_q = torch.min(\n"
            "            self.agent.qf1(obs_flat, new_actions, task_z.detach()),\n"
            "            self.agent.qf2(obs_flat, new_actions, task_z.detach()),\n"
            "        )\n"
            "        v_target = min_q - log_pi\n"
            "        vf_loss = F.mse_loss(v_pred, v_target.detach())\n"
            "        self.vf_optimizer.zero_grad()\n"
            "        vf_loss.backward()\n"
            "        self.vf_optimizer.step()\n"
            "        ptu.soft_update_from_to(\n"
            "            self.agent.vf, self.agent.target_vf, self.soft_target_tau)\n"
            "\n"
            "        # Policy loss\n"
            "        policy_loss = (log_pi - min_q).mean()\n"
            "        mean_reg = 1e-3 * (policy_mean ** 2).mean()\n"
            "        std_reg = 1e-3 * (policy_log_std ** 2).mean()\n"
            "        policy_loss = policy_loss + mean_reg + std_reg\n"
            "        self.policy_optimizer.zero_grad()\n"
            "        policy_loss.backward()\n"
            "        self.policy_optimizer.step()\n"
            "\n"
            "    @property\n"
            "    def networks(self):\n"
            "        return self.agent.networks\n"
        ),
    },
]
