"""VariBAD baseline: GRU encoder + reward prediction auxiliary loss.

Key differences from PEARL:
- Sequential context processing via GRU (instead of permutation-invariant PoG)
- Belief state = GRU hidden state
- Reward decoder: predicts reward from (state, action, belief) for auxiliary loss
- ELBO-style loss: reward prediction + KL on belief

Training samples ordered replay trajectories with sequence=True, conditions the
GRU posterior q(z_t | tau_1:t) on chronological context, and reconstructs
rewards at every trajectory step.
"""

OPS = [
    {
        "op": "replace",
        "file": "oyster/custom_meta_rl.py",
        "start_line": 357,
        "end_line": 494,
        "content": (
            "# =====================================================================\n"
            "# EDITABLE — Custom imports\n"
            "# =====================================================================\n"
            "\n"
            "\n"
            "# =====================================================================\n"
            "# EDITABLE — Custom Meta-RL Agent\n"
            "# =====================================================================\n"
            "class GRUContextEncoder(nn.Module):\n"
            "    \"\"\"GRU-based context encoder for sequential processing.\"\"\"\n"
            "\n"
            "    def __init__(self, input_dim, hidden_dim, latent_dim):\n"
            "        super().__init__()\n"
            "        self.hidden_dim = hidden_dim\n"
            "        self.latent_dim = latent_dim\n"
            "        # Pre-process transitions with MLP\n"
            "        self.fc_pre = nn.Sequential(\n"
            "            nn.Linear(input_dim, hidden_dim),\n"
            "            nn.ReLU(),\n"
            "            nn.Linear(hidden_dim, hidden_dim),\n"
            "            nn.ReLU(),\n"
            "        )\n"
            "        self.gru = nn.GRU(hidden_dim, hidden_dim, batch_first=True)\n"
            "        # Output mean and logvar for latent\n"
            "        self.fc_mean = nn.Linear(hidden_dim, latent_dim)\n"
            "        self.fc_logvar = nn.Linear(hidden_dim, latent_dim)\n"
            "        self.register_buffer('hidden', torch.zeros(1, 1, hidden_dim))\n"
            "\n"
            "    def reset(self, num_tasks=1):\n"
            "        self.hidden = self.hidden.new_zeros(1, num_tasks, self.hidden_dim)\n"
            "\n"
            "    def forward(self, context, return_sequence=False):\n"
            "        \"\"\"context: (num_tasks, seq_len, feat_dim).\"\"\"\n"
            "        t, s, f = context.size()\n"
            "        x = context.reshape(t * s, f)\n"
            "        x = self.fc_pre(x)\n"
            "        x = x.view(t, s, -1)\n"
            "        out, hn = self.gru(x, self.hidden)\n"
            "        self.hidden = hn.detach()\n"
            "        mean = self.fc_mean(out)\n"
            "        logvar = self.fc_logvar(out)\n"
            "        if return_sequence:\n"
            "            return mean, logvar\n"
            "        return mean[:, -1, :], logvar[:, -1, :]\n"
            "\n"
            "\n"
            "class RewardDecoder(nn.Module):\n"
            "    \"\"\"Predict reward from (state, action, belief/z).\"\"\"\n"
            "\n"
            "    def __init__(self, obs_dim, action_dim, latent_dim, hidden_dim=200):\n"
            "        super().__init__()\n"
            "        self.net = nn.Sequential(\n"
            "            nn.Linear(obs_dim + action_dim + latent_dim, hidden_dim),\n"
            "            nn.ReLU(),\n"
            "            nn.Linear(hidden_dim, hidden_dim),\n"
            "            nn.ReLU(),\n"
            "            nn.Linear(hidden_dim, 1),\n"
            "        )\n"
            "\n"
            "    def forward(self, obs, action, z):\n"
            "        return self.net(torch.cat([obs, action, z], dim=-1))\n"
            "\n"
            "\n"
            "class CustomMetaRLAgent(nn.Module):\n"
            "    \"\"\"VariBAD agent: GRU encoder + reward decoder.\"\"\"\n"
            "\n"
            "    def __init__(self, obs_dim, action_dim, latent_dim=5, net_size=300,\n"
            "                 reward_dim=1, use_next_obs_in_context=False, **kwargs):\n"
            "        super().__init__()\n"
            "        self.obs_dim = obs_dim\n"
            "        self.action_dim = action_dim\n"
            "        self.latent_dim = latent_dim\n"
            "        self.use_next_obs_in_context = use_next_obs_in_context\n"
            "        self.sparse_rewards = kwargs.get('sparse_rewards', False)\n"
            "\n"
            "        context_input_dim = obs_dim + action_dim + reward_dim\n"
            "        if use_next_obs_in_context:\n"
            "            context_input_dim += obs_dim\n"
            "\n"
            "        self.encoder = GRUContextEncoder(\n"
            "            context_input_dim, hidden_dim=200, latent_dim=latent_dim)\n"
            "        self.reward_decoder = RewardDecoder(\n"
            "            obs_dim, action_dim, latent_dim, hidden_dim=200)\n"
            "\n"
            "        self.policy = build_policy(obs_dim, action_dim, latent_dim, net_size)\n"
            "        self.qf1 = build_qf(obs_dim, action_dim, latent_dim, net_size)\n"
            "        self.qf2 = build_qf(obs_dim, action_dim, latent_dim, net_size)\n"
            "        self.vf = build_vf(obs_dim, latent_dim, net_size)\n"
            "        self.target_vf = copy.deepcopy(self.vf)\n"
            "\n"
            "        self.register_buffer('z', torch.zeros(1, latent_dim))\n"
            "        self.register_buffer('z_means', torch.zeros(1, latent_dim))\n"
            "        self.register_buffer('z_logvars', torch.zeros(1, latent_dim))\n"
            "        self._context = None\n"
            "\n"
            "    def clear_context(self, num_tasks=1):\n"
            "        self.z = ptu.zeros(num_tasks, self.latent_dim)\n"
            "        self.z_means = ptu.zeros(num_tasks, self.latent_dim)\n"
            "        self.z_logvars = ptu.zeros(num_tasks, self.latent_dim)\n"
            "        self.encoder.reset(num_tasks)\n"
            "        self._context = None\n"
            "\n"
            "    def clear_z(self, num_tasks=1):\n"
            "        self.clear_context(num_tasks)\n"
            "\n"
            "    def sample_z(self):\n"
            "        std = torch.exp(0.5 * self.z_logvars)\n"
            "        eps = torch.randn_like(std)\n"
            "        self.z = self.z_means + eps * std\n"
            "\n"
            "    @property\n"
            "    def context(self):\n"
            "        return self._context\n"
            "\n"
            "    def update_context(self, inputs):\n"
            "        o, a, r, no, d, info = inputs\n"
            "        if self.sparse_rewards:\n"
            "            r = info.get('sparse_reward', r)\n"
            "        o = ptu.from_numpy(o[None, None, ...])\n"
            "        a = ptu.from_numpy(a[None, None, ...])\n"
            "        r = ptu.from_numpy(np.array([r])[None, None, ...])\n"
            "        no = ptu.from_numpy(no[None, None, ...])\n"
            "        if self.use_next_obs_in_context:\n"
            "            data = torch.cat([o, a, r, no], dim=2)\n"
            "        else:\n"
            "            data = torch.cat([o, a, r], dim=2)\n"
            "        if self._context is None:\n"
            "            self._context = data\n"
            "        else:\n"
            "            self._context = torch.cat([self._context, data], dim=1)\n"
            "\n"
            "    def infer_posterior(self, context):\n"
            "        self.encoder.reset(context.size(0))\n"
            "        mean, logvar = self.encoder(context)\n"
            "        self.z_means = mean\n"
            "        self.z_logvars = logvar\n"
            "        self.sample_z()\n"
            "\n"
            "    def adapt(self):\n"
            "        if self._context is not None:\n"
            "            self.infer_posterior(self._context)\n"
            "\n"
            "    def compute_kl_div(self):\n"
            "        \"\"\"KL(q(z|c) || N(0, I)).\"\"\"\n"
            "        kl = -0.5 * torch.sum(\n"
            "            1 + self.z_logvars - self.z_means.pow(2) - self.z_logvars.exp())\n"
            "        return kl\n"
            "\n"
            "    def get_action(self, obs, deterministic=False):\n"
            "        z = self.z\n"
            "        obs_t = ptu.from_numpy(obs[None])\n"
            "        in_ = torch.cat([obs_t, z], dim=1)\n"
            "        return self.policy.get_action(in_, deterministic=deterministic)\n"
            "\n"
            "    def forward(self, obs, context):\n"
            "        self.infer_posterior(context)\n"
            "        task_z = self.z\n"
            "        t, b, _ = obs.size()\n"
            "        obs = obs.view(t * b, -1)\n"
            "        task_z_rep = [z.repeat(b, 1) for z in task_z]\n"
            "        task_z_rep = torch.cat(task_z_rep, dim=0)\n"
            "        in_ = torch.cat([obs, task_z_rep.detach()], dim=1)\n"
            "        policy_outputs = self.policy(\n"
            "            in_, reparameterize=True, return_log_prob=True)\n"
            "        return policy_outputs, task_z_rep\n"
            "\n"
            "    def set_num_steps_total(self, n):\n"
            "        self.policy.set_num_steps_total(n)\n"
            "\n"
            "    def detach_z(self):\n"
            "        self.z = self.z.detach()\n"
            "\n"
            "    @property\n"
            "    def networks(self):\n"
            "        return [self.policy, self.qf1, self.qf2,\n"
            "                self.vf, self.target_vf, self.reward_decoder]\n"
            "\n"
            "\n"
            "class CustomMetaRLAlgorithm:\n"
            "    \"\"\"VariBAD: SAC + ELBO (reward prediction + KL) loss.\"\"\"\n"
            "\n"
            "    def __init__(self, agent, env, train_tasks, eval_tasks,\n"
            "                 replay_buffer, enc_replay_buffer, config):\n"
            "        self.agent = agent\n"
            "        self.env = env\n"
            "        self.train_tasks = train_tasks\n"
            "        self.eval_tasks = eval_tasks\n"
            "        self.replay_buffer = replay_buffer\n"
            "        self.enc_replay_buffer = enc_replay_buffer\n"
            "        self.config = config\n"
            "\n"
            "        self.sampler = InPlacePathSampler(\n"
            "            env=env, policy=agent,\n"
            "            max_path_length=config['max_path_length'],\n"
            "        )\n"
            "\n"
            "        self.batch_size = config.get('batch_size', 256)\n"
            "        self.meta_batch = config.get('meta_batch', 16)\n"
            "        self.discount = config.get('discount', 0.99)\n"
            "        self.reward_scale = config.get('reward_scale', 5.0)\n"
            "        self.kl_lambda = config.get('kl_lambda', 0.1)\n"
            "        self.reward_pred_weight = 1.0\n"
            "        self.soft_target_tau = config.get('soft_target_tau', 0.005)\n"
            "        self.sparse_rewards = config.get('sparse_rewards', False)\n"
            "        self.use_next_obs_in_context = config.get('use_next_obs_in_context', False)\n"
            "        self.embedding_batch_size = config.get('embedding_batch_size', 64)\n"
            "        self.embedding_mini_batch_size = config.get('embedding_mini_batch_size', 64)\n"
            "        self.num_tasks_sample = config.get('num_tasks_sample', 5)\n"
            "        self.num_steps_prior = config.get('num_steps_prior', 400)\n"
            "        self.num_steps_posterior = config.get('num_steps_posterior', 0)\n"
            "        self.num_extra_rl_steps_posterior = config.get('num_extra_rl_steps_posterior', 400)\n"
            "        self.num_train_steps_per_itr = config.get('num_train_steps_per_itr', 2000)\n"
            "        self.update_post_train = config.get('update_post_train', 1)\n"
            "\n"
            "        lr = 3e-4\n"
            "        encoder_params = list(agent.encoder.parameters()) + list(agent.reward_decoder.parameters())\n"
            "        self.policy_optimizer = optim.Adam(agent.policy.parameters(), lr=lr)\n"
            "        self.qf1_optimizer = optim.Adam(agent.qf1.parameters(), lr=lr)\n"
            "        self.qf2_optimizer = optim.Adam(agent.qf2.parameters(), lr=lr)\n"
            "        self.vf_optimizer = optim.Adam(agent.vf.parameters(), lr=lr)\n"
            "        self.encoder_optimizer = optim.Adam(encoder_params, lr=lr)\n"
            "\n"
            "    def collect_initial_data(self):\n"
            "        num_initial_steps = self.config.get('num_initial_steps', 200)\n"
            "        for idx in self.train_tasks:\n"
            "            self.env.reset_task(idx)\n"
            "            collect_data(\n"
            "                self.agent, self.env, self.sampler,\n"
            "                self.replay_buffer, self.enc_replay_buffer,\n"
            "                idx, num_initial_steps, 1, np.inf,\n"
            "                add_to_enc_buffer=True, config=self.config,\n"
            "            )\n"
            "\n"
            "    def train_iteration(self, iteration_idx):\n"
            "        for i in range(self.num_tasks_sample):\n"
            "            idx = np.random.randint(len(self.train_tasks))\n"
            "            self.env.reset_task(idx)\n"
            "            self.enc_replay_buffer.task_buffers[idx].clear()\n"
            "            if self.num_steps_prior > 0:\n"
            "                collect_data(\n"
            "                    self.agent, self.env, self.sampler,\n"
            "                    self.replay_buffer, self.enc_replay_buffer,\n"
            "                    idx, self.num_steps_prior, 1, np.inf,\n"
            "                    config=self.config,\n"
            "                )\n"
            "            if self.num_steps_posterior > 0:\n"
            "                collect_data(\n"
            "                    self.agent, self.env, self.sampler,\n"
            "                    self.replay_buffer, self.enc_replay_buffer,\n"
            "                    idx, self.num_steps_posterior, 1, self.update_post_train,\n"
            "                    config=self.config,\n"
            "                )\n"
            "            if self.num_extra_rl_steps_posterior > 0:\n"
            "                collect_data(\n"
            "                    self.agent, self.env, self.sampler,\n"
            "                    self.replay_buffer, self.enc_replay_buffer,\n"
            "                    idx, self.num_extra_rl_steps_posterior, 1,\n"
            "                    self.update_post_train,\n"
            "                    add_to_enc_buffer=False, config=self.config,\n"
            "                )\n"
            "\n"
            "        for _ in range(self.num_train_steps_per_itr):\n"
            "            indices = np.random.choice(\n"
            "                self.train_tasks, self.meta_batch)\n"
            "            self._take_step(indices)\n"
            "        return {}\n"
            "\n"
            "    def _sample_ordered_context_from_buffer(self, indices, batch_size):\n"
            "        \"\"\"Sample chronological trajectory context for VariBAD.\n"
            "\n"
            "        Cap batch_size at max_path_length so each task's context comes\n"
            "        from a SINGLE trajectory. oyster's random_sequence concatenates\n"
            "        independent trajectories without resetting the GRU hidden state\n"
            "        at episode boundaries, polluting the per-step posterior used by\n"
            "        the ELBO reward decoder.\n"
            "        \"\"\"\n"
            "        if not hasattr(indices, '__iter__'):\n"
            "            indices = [indices]\n"
            "        max_path = self.config.get('max_path_length', batch_size)\n"
            "        bsz = min(batch_size, max_path)\n"
            "        batches = [ptu.np_to_pytorch_batch(\n"
            "            self.enc_replay_buffer.random_batch(\n"
            "                idx, batch_size=bsz, sequence=True))\n"
            "            for idx in indices]\n"
            "        context = [unpack_batch(batch, sparse_reward=self.sparse_rewards)\n"
            "                   for batch in batches]\n"
            "        context = [[x[i] for x in context] for i in range(len(context[0]))]\n"
            "        context = [torch.cat(x, dim=0) for x in context]\n"
            "        if self.use_next_obs_in_context:\n"
            "            return torch.cat(context[:-1], dim=2)\n"
            "        return torch.cat(context[:-2], dim=2)\n"
            "\n"
            "    def _take_step(self, indices):\n"
            "        mb_size = self.embedding_mini_batch_size\n"
            "        num_updates = self.embedding_batch_size // mb_size\n"
            "\n"
            "        context_batch = self._sample_ordered_context_from_buffer(\n"
            "            indices, self.embedding_batch_size)\n"
            "        self.agent.clear_z(num_tasks=len(indices))\n"
            "\n"
            "        for i in range(num_updates):\n"
            "            context = context_batch[:, i * mb_size: i * mb_size + mb_size, :]\n"
            "            self._update(indices, context)\n"
            "            self.agent.detach_z()\n"
            "\n"
            "    def _sample_sac_batch_with_sparse(self, indices):\n"
            "        \"\"\"Sample RL batch; also return sparse rewards when needed.\"\"\"\n"
            "        batches = [ptu.np_to_pytorch_batch(\n"
            "            self.replay_buffer.random_batch(idx, batch_size=self.batch_size))\n"
            "            for idx in indices]\n"
            "        unpacked = [unpack_batch(b) for b in batches]\n"
            "        unpacked = [[x[i] for x in unpacked] for i in range(len(unpacked[0]))]\n"
            "        unpacked = [torch.cat(x, dim=0) for x in unpacked]\n"
            "        obs, actions, rewards, next_obs, terms = unpacked\n"
            "        if self.sparse_rewards:\n"
            "            sparse_r = torch.cat(\n"
            "                [b['sparse_rewards'][None, ...] for b in batches], dim=0)\n"
            "        else:\n"
            "            sparse_r = rewards\n"
            "        return obs, actions, rewards, next_obs, terms, sparse_r\n"
            "\n"
            "    def _update(self, indices, context):\n"
            "        num_tasks = len(indices)\n"
            "        obs, actions, rewards, next_obs, terms, _ = \\\n"
            "            self._sample_sac_batch_with_sparse(indices)\n"
            "\n"
            "        # Forward: encode context and get policy outputs\n"
            "        policy_outputs, task_z = self.agent(obs, context)\n"
            "        new_actions, policy_mean, policy_log_std, log_pi = policy_outputs[:4]\n"
            "\n"
            "        t, b, _ = obs.size()\n"
            "        obs_flat = obs.view(t * b, -1)\n"
            "        actions_flat = actions.view(t * b, -1)\n"
            "        next_obs_flat = next_obs.view(t * b, -1)\n"
            "\n"
            "        q1_pred = self.agent.qf1(obs_flat, actions_flat, task_z)\n"
            "        q2_pred = self.agent.qf2(obs_flat, actions_flat, task_z)\n"
            "        v_pred = self.agent.vf(obs_flat, task_z.detach())\n"
            "        with torch.no_grad():\n"
            "            target_v = self.agent.target_vf(next_obs_flat, task_z)\n"
            "\n"
            "        # --- Encoder loss: KL + reward prediction ---\n"
            "        # Per-step ELBO with z_seq forces the GRU to predict rewards\n"
            "        # from partial-belief z_seq[k] (built from only first k context\n"
            "        # transitions) on cheetah-vel where target velocity is barely\n"
            "        # observable from a single (s,a) — encoder fails to converge.\n"
            "        # Fall back to OLD's design: single-posterior z (last step) +\n"
            "        # decoder predicts the SAC batch's rewards. Ordered context\n"
            "        # still helps the GRU build a coherent posterior.\n"
            "        self.encoder_optimizer.zero_grad()\n"
            "\n"
            "        kl_div = -0.5 * torch.sum(\n"
            "            1 + self.agent.z_logvars - self.agent.z_means.pow(2)\n"
            "            - self.agent.z_logvars.exp())\n"
            "\n"
            "        z_for_pred = self.agent.z\n"
            "        z_rep = z_for_pred.unsqueeze(1).expand(-1, b, -1).reshape(t * b, -1)\n"
            "        rewards_flat = rewards.view(t * b, -1)\n"
            "        reward_pred = self.agent.reward_decoder(\n"
            "            obs_flat, actions_flat, z_rep)\n"
            "        reward_pred_loss = F.mse_loss(reward_pred, rewards_flat)\n"
            "\n"
            "        encoder_loss = (self.kl_lambda * kl_div +\n"
            "                        self.reward_pred_weight * reward_pred_loss)\n"
            "        encoder_loss.backward(retain_graph=True)\n"
            "\n"
            "        # Q-function loss\n"
            "        self.qf1_optimizer.zero_grad()\n"
            "        self.qf2_optimizer.zero_grad()\n"
            "        rewards_scaled = rewards_flat * self.reward_scale\n"
            "        terms_flat = terms.view(self.batch_size * num_tasks, -1)\n"
            "        q_target = rewards_scaled + (1. - terms_flat) * self.discount * target_v\n"
            "        qf_loss = (torch.mean((q1_pred - q_target) ** 2) +\n"
            "                   torch.mean((q2_pred - q_target) ** 2))\n"
            "        qf_loss.backward()\n"
            "        self.qf1_optimizer.step()\n"
            "        self.qf2_optimizer.step()\n"
            "        self.encoder_optimizer.step()\n"
            "\n"
            "        # V-function loss\n"
            "        min_q = torch.min(\n"
            "            self.agent.qf1(obs_flat, new_actions, task_z.detach()),\n"
            "            self.agent.qf2(obs_flat, new_actions, task_z.detach()),\n"
            "        )\n"
            "        v_target = min_q - log_pi\n"
            "        vf_loss = F.mse_loss(v_pred, v_target.detach())\n"
            "        self.vf_optimizer.zero_grad()\n"
            "        vf_loss.backward()\n"
            "        self.vf_optimizer.step()\n"
            "        ptu.soft_update_from_to(\n"
            "            self.agent.vf, self.agent.target_vf, self.soft_target_tau)\n"
            "\n"
            "        # Policy loss\n"
            "        policy_loss = (log_pi - min_q).mean()\n"
            "        mean_reg = 1e-3 * (policy_mean ** 2).mean()\n"
            "        std_reg = 1e-3 * (policy_log_std ** 2).mean()\n"
            "        policy_loss = policy_loss + mean_reg + std_reg\n"
            "        self.policy_optimizer.zero_grad()\n"
            "        policy_loss.backward()\n"
            "        self.policy_optimizer.step()\n"
            "\n"
            "    @property\n"
            "    def networks(self):\n"
            "        return self.agent.networks\n"
        ),
    },
]
