_BODY = '@torch.no_grad()\ndef sample_dbim(\n    denoiser,\n    diffusion,\n    x,\n    ts,\n    eta=1.0,\n    mask=None,\n    seed=None,\n    **kwargs,\n):\n    x_T = x\n    path = []\n    pred_x0 = []\n    ones = x.new_ones([x.shape[0]])\n    indices = tqdm(range(len(ts) - 1), disable=(dist.get_rank() != 0))\n    generator = BatchedSeedGenerator(seed)\n    x0_prev = denoiser(x, diffusion.t_max * ones)\n    if mask is not None: x0_prev = x0_prev * mask + x_T * (1 - mask)\n    first_noise = generator.randn_like(x0_prev)\n    x = diffusion.bridge_sample(x0_prev, x_T, ts[0] * ones, first_noise)\n    path.append(x.detach().cpu()); pred_x0.append(x0_prev.detach().cpu())\n    prev_x0_raw = x0_prev; dims = tuple(range(1, x.ndim)); total_steps = len(ts) - 1\n    for i in indices:\n        s, t = ts[i], ts[i + 1]\n        x0_raw = denoiser(x, s * ones)\n        if mask is not None: x0_raw = x0_raw * mask + x_T * (1 - mask)\n        phase = float(i + 1) / float(max(total_steps, 1))\n        delta = x0_raw - x0_prev; cur = delta.pow(2).mean(dim=dims, keepdim=True)\n        vel = (x0_raw - prev_x0_raw).pow(2).mean(dim=dims, keepdim=True)\n        # second-order predictor with endpoint-aware contraction\n        extrap = x0_raw + (0.16 * (1.0 - phase) ** 1.2) * (x0_raw - x0_prev)\n        gate = (0.55 + 0.25 * phase) * (cur / (cur + vel + 1e-8)).clamp(0.15, 0.85)\n        x0_hat = gate * x0_raw + (1 - gate) * extrap\n        if i >= total_steps - 2: x0_hat = 0.88 * x0_raw + 0.12 * x0_prev\n        a_s, b_s, c_s = [append_dims(v, x0_hat.ndim) for v in diffusion.noise_schedule.get_abc(s * ones)]; a_t, b_t, c_t = [append_dims(v, x0_hat.ndim) for v in diffusion.noise_schedule.get_abc(t * ones)]\n        _, _, rho_s, _ = [append_dims(v, x0_hat.ndim) for v in diffusion.noise_schedule.get_alpha_rho(s * ones)]; alpha_t, _, rho_t, _ = [append_dims(v, x0_hat.ndim) for v in diffusion.noise_schedule.get_alpha_rho(t * ones)]\n        # front-loaded stochasticity, nearly deterministic tail\n        adapt = eta * (0.42 * (1.0 - phase) ** 1.6)\n        omega_st = adapt * (alpha_t * rho_t) * (1 - rho_t**2 / rho_s**2).sqrt(); tmp_var = (c_t**2 - omega_st**2).clamp_min(0).sqrt() / c_s\n        noise = generator.randn_like(x0_hat)\n        x = (b_t - tmp_var * b_s) * x0_hat + (a_t - tmp_var * a_s) * x_T + tmp_var * x + (1 if i < len(ts) - 3 else 0) * omega_st * noise\n        path.append(x.detach().cpu()); pred_x0.append(x0_hat.detach().cpu()); prev_x0_raw = x0_prev; x0_prev = x0_raw\n    return x, path, len(ts) - 1, pred_x0, ts, first_noise\n'

OPS = [
    {
        "op": "replace",
        "file": "dbim-codebase/ddbm/karras_diffusion.py",
        "start_line": 448,
        "end_line": 463,
        "content": _BODY,
    },
]
