_BODY = '@torch.no_grad()\ndef sample_dbim(\n    denoiser,\n    diffusion,\n    x,\n    ts,\n    eta=1.0,\n    mask=None,\n    seed=None,\n    **kwargs,\n):\n    # =================================================================================\n    # Novel sampler: Adaptive Stochasticity with Exponential Decay (ASED)\n    # =================================================================================\n    x_T = x\n    path = []\n    pred_x0 = []\n    ones = x.new_ones([x.shape[0]])\n    indices = range(len(ts) - 1)\n    indices = tqdm(indices, disable=(dist.get_rank() != 0))\n    nfe = 0\n    generator = BatchedSeedGenerator(seed)\n    # initial step\n    x0_hat = denoiser(x, diffusion.t_max * ones)\n    if mask is not None:\n        x0_hat = x0_hat * mask + x_T * (1 - mask)\n    noise = generator.randn_like(x0_hat)\n    first_noise = noise\n    x = diffusion.bridge_sample(x0_hat, x_T, ts[0] * ones, noise)\n    path.append(x.detach().cpu())\n    pred_x0.append(x0_hat.detach().cpu())\n    nfe += 1\n    # momentum for x0_hat\n    x0_hat_prev = x0_hat\n    for idx, i in enumerate(indices):\n        s = ts[i]\n        t = ts[i + 1]\n        # exponential decay of stochasticity\n        eta_adapt = eta * (0.5 ** (idx / (len(ts)-2))) if i != len(ts)-2 else 0.0\n        # denoiser call\n        x0_hat = denoiser(x, s * ones)\n        if mask is not None:\n            x0_hat = x0_hat * mask + x_T * (1 - mask)\n        # momentum blending: combine with previous x0_hat\n        x0_hat = 0.7 * x0_hat + 0.3 * x0_hat_prev\n        x0_hat_prev = x0_hat\n        # compute coefficients\n        a_s, b_s, c_s = [append_dims(item, x0_hat.ndim) for item in diffusion.noise_schedule.get_abc(s * ones)]\n        a_t, b_t, c_t = [append_dims(item, x0_hat.ndim) for item in diffusion.noise_schedule.get_abc(t * ones)]\n        _, _, rho_s, _ = [append_dims(item, x0_hat.ndim) for item in diffusion.noise_schedule.get_alpha_rho(s * ones)]\n        alpha_t, _, rho_t, _ = [append_dims(item, x0_hat.ndim) for item in diffusion.noise_schedule.get_alpha_rho(t * ones)]\n        omega_st = eta_adapt * (alpha_t * rho_t) * (1 - rho_t**2 / rho_s**2).sqrt()\n        tmp_var = (c_t**2 - omega_st**2).sqrt() / c_s\n        coeff_xs = tmp_var\n        coeff_x0_hat = b_t - tmp_var * b_s\n        coeff_xT = a_t - tmp_var * a_s\n        noise_step = generator.randn_like(x0_hat) if i != len(ts)-2 else None\n        x = coeff_x0_hat * x0_hat + coeff_xT * x_T + coeff_xs * x\n        if noise_step is not None:\n            x = x + omega_st * noise_step\n        path.append(x.detach().cpu())\n        pred_x0.append(x0_hat.detach().cpu())\n        nfe += 1\n    nfe = len(ts) - 1\n    return x, path, nfe, pred_x0, ts, first_noise\n'

OPS = [
    {
        "op": "replace",
        "file": "dbim-codebase/ddbm/karras_diffusion.py",
        "start_line": 448,
        "end_line": 463,
        "content": _BODY,
    },
]
