_BODY = '@torch.no_grad()\ndef sample_dbim(\n    denoiser,\n    diffusion,\n    x,\n    ts,\n    eta=1.0,\n    mask=None,\n    seed=None,\n    **kwargs,\n):\n    import math as _math\n    x_T = x.clone()\n    path = []\n    pred_x0 = []\n    ones = x.new_ones([x.shape[0]])\n    N = len(ts) - 1\n    nfe = N\n\n    if seed is not None:\n        _s = seed\n        if hasattr(_s, "flatten"): _s = _s.flatten()[0]\n        if hasattr(_s, "item"): _s = _s.item()\n        g = torch.Generator(device=x.device).manual_seed(int(_s) + 7)\n    else:\n        g = None\n\n    def _rn(ref):\n        if g is None:\n            return torch.randn_like(ref)\n        return torch.randn(ref.shape, device=ref.device, dtype=ref.dtype, generator=g)\n\n    first_noise = _rn(x)\n    sigma_T = float(ts[0])\n\n    for i in range(N):\n        sigma_t = float(ts[i])\n        sigma_s = float(ts[i + 1])\n\n        x0 = denoiser(x, ts[i] * ones)\n        pred_x0.append(x0)\n        path.append(x)\n\n        # Final step or zero-time: collapse to x0 prediction\n        if i == N - 1 or sigma_s <= 1e-8:\n            x = x0\n            continue\n\n        # VE bridge coefficients (Brownian bridge from x_T at sigma_T to x_0 at 0)\n        r_t = (sigma_t / sigma_T) ** 2\n        r_s = (sigma_s / sigma_T) ** 2\n        a_x0_t = 1.0 - r_t\n        a_xT_t = r_t\n        bstd_t = (sigma_t ** 2 * max(0.0, 1.0 - r_t)) ** 0.5\n        a_x0_s = 1.0 - r_s\n        a_xT_s = r_s\n        bstd_s_sq = (sigma_s ** 2) * max(0.0, 1.0 - r_s)\n        bstd_s = bstd_s_sq ** 0.5\n\n        # Infer the bridge noise from current state and x0 prediction (DBIM reparam)\n        if bstd_t > 1e-8:\n            eps_hat = (x - a_x0_t * x0 - a_xT_t * x_T) / bstd_t\n        else:\n            eps_hat = torch.zeros_like(x)\n\n        # ----- Novel mid-peaked stochasticity schedule -----\n        # Low at start (x already noisy from x_T), peaked mid-trajectory\n        # for exploration, then forced to 0 in last 2 steps (ECSI-like sharpness).\n        if N <= 2:\n            eta_i = 0.0\n        else:\n            progress = (i + 0.5) / N\n            # Inverted parabola peaked at progress=0.55 (slight late skew)\n            peak = 0.55\n            shape = 1.0 - ((progress - peak) / max(peak, 1.0 - peak)) ** 2\n            shape = max(0.0, shape)\n            eta_i = float(eta) * shape\n            # Endpoint sharpening: kill stochasticity on last two updates\n            if i >= N - 2:\n                eta_i = 0.0\n\n        sigma_inj = eta_i * bstd_s\n        det_coef = (max(0.0, bstd_s_sq - sigma_inj ** 2)) ** 0.5\n\n        noise = _rn(x)\n        x = a_x0_s * x0 + a_xT_s * x_T + det_coef * eps_hat + sigma_inj * noise\n\n    return x, path, nfe, pred_x0, ts, first_noise\n'

OPS = [
    {
        "op": "replace",
        "file": "dbim-codebase/ddbm/karras_diffusion.py",
        "start_line": 448,
        "end_line": 463,
        "content": _BODY,
    },
]
