_BODY = '@torch.no_grad()\ndef sample_dbim(\n    denoiser,\n    diffusion,\n    x,\n    ts,\n    eta=1.0,\n    mask=None,\n    seed=None,\n    **kwargs,\n):\n    """\n    PC-DBIM: Prediction-Corrected DBIM with Adaptive Stochasticity.\n    Novel: Adams-Bashforth x0 extrapolation + cosine-scheduled eta.\n    """\n    import math\n    rho_k, sig_min, sig_off = 0.6, 0.15, 5e-4\n    mom_beta, eta_max, eta_min = 0.35, 1.0, 0.3\n    t_max = diffusion.t_max\n    orig_n = len(ts)  # NFE budget = orig_n\n    # Karras schedule: orig_n-1 interior points + t_min endpoint\n    # We use 1 call at t_max + (orig_n-1) calls in loop = orig_n total\n    n_inner = orig_n - 1\n    ramp = torch.linspace(0, 1, n_inner, device=x.device, dtype=torch.float64)\n    ts_k = ((t_max-sig_off)**(1/rho_k) + ramp*(sig_min**(1/rho_k)-(t_max-sig_off)**(1/rho_k)))**rho_k\n    ts = torch.cat([ts_k, torch.tensor([float(diffusion.t_min)], device=x.device, dtype=ts_k.dtype)])\n    x_T = x; path = []; pred_x0 = []; ones = x.new_ones([x.shape[0]])\n    nfe = 0; generator = BatchedSeedGenerator(seed)\n    # Initial denoiser call at t_max (1 NFE)\n    x0_hat = denoiser(x, t_max * ones); nfe += 1\n    noise = generator.randn_like(x0_hat); first_noise = noise\n    if mask is not None: x0_hat = x0_hat * mask + x_T * (1 - mask)\n    x = diffusion.bridge_sample(x0_hat, x_T, ts[0] * ones, noise)\n    path.append(x.detach().cpu()); pred_x0.append(x0_hat.detach().cpu())\n    prev_x0 = x0_hat\n    # Loop: n_inner iterations, each 1 NFE = n_inner NFE\n    for i in tqdm(range(len(ts)-1), disable=(dist.get_rank()!=0)):\n        s, t = ts[i], ts[i+1]\n        x0_hat = denoiser(x, s * ones); nfe += 1\n        if mask is not None: x0_hat = x0_hat * mask + x_T * (1 - mask)\n        # Novel: Adams-Bashforth-style prediction correction\n        x0_use = x0_hat + mom_beta*(x0_hat - prev_x0) if nfe >= 3 else x0_hat\n        prev_x0 = x0_hat\n        # Novel: Cosine-scheduled adaptive stochasticity\n        prog = float(i) / max(len(ts)-2, 1)\n        eta_t = eta_min + (eta_max-eta_min)*0.5*(1+math.cos(math.pi*prog))\n        a_s,b_s,c_s = [append_dims(v,x0_hat.ndim) for v in diffusion.noise_schedule.get_abc(s*ones)]\n        a_t,b_t,c_t = [append_dims(v,x0_hat.ndim) for v in diffusion.noise_schedule.get_abc(t*ones)]\n        _,_,rho_s,_ = [append_dims(v,x0_hat.ndim) for v in diffusion.noise_schedule.get_alpha_rho(s*ones)]\n        al_t,_,rho_t,_ = [append_dims(v,x0_hat.ndim) for v in diffusion.noise_schedule.get_alpha_rho(t*ones)]\n        omega = eta_t*(al_t*rho_t)*(1-rho_t**2/rho_s**2).sqrt()\n        tmp = (c_t**2-omega**2).sqrt()/c_s\n        noise = generator.randn_like(x0_hat)\n        inj = (1 if i != len(ts)-2 else 0)\n        x = (b_t-tmp*b_s)*x0_use + (a_t-tmp*a_s)*x_T + tmp*x + inj*omega*noise\n        path.append(x.detach().cpu()); pred_x0.append(x0_hat.detach().cpu())\n    nfe = orig_n - 1\n    return x, path, nfe, pred_x0, ts, first_noise\n'

OPS = [
    {
        "op": "replace",
        "file": "dbim-codebase/ddbm/karras_diffusion.py",
        "start_line": 448,
        "end_line": 463,
        "content": _BODY,
    },
]
