_BODY = '@torch.no_grad()\ndef sample_dbim(\n    denoiser,\n    diffusion,\n    x,\n    ts,\n    eta=1.0,\n    mask=None,\n    seed=None,\n    **kwargs,\n):\n# EMPB-QSD: Exact Marginal-Preserving Bridge with Quadratic Stochasticity Decay\n    # Novel: (1) exact coefficient transition vs Euler discretization,\n    # (2) proportional noise injection eta_i (dt-independent, always valid),\n    # (3) quadratic eta decay for smooth stochasticity scheduling.\n\n    rho_k = 0.6; sigma_min = 0.15; sigma_max_offset = 5e-4; eta_max = 0.65\n    t_max = diffusion.t_max; ns = diffusion.noise_schedule\n\n    n = len(ts)\n    ramp = torch.linspace(0.0, 1.0, n, device=x.device, dtype=torch.float64)\n    ts_k = ((t_max - sigma_max_offset) ** (1.0 / rho_k) + ramp * (sigma_min ** (1.0 / rho_k) - (t_max - sigma_max_offset) ** (1.0 / rho_k))) ** rho_k\n    ts = torch.cat([ts_k, torch.tensor([float(diffusion.t_min)], device=x.device, dtype=ts_k.dtype)])\n\n    x_T = x; path = [x.detach().cpu()]; pred_x0 = []\n    ones = x.new_ones([x.shape[0]])\n    n_steps = len(ts) - 1\n    indices = range(n_steps)\n    indices = tqdm(indices, disable=(dist.get_rank() != 0))\n    generator = BatchedSeedGenerator(seed)\n    first_noise = generator.randn_like(x)\n    nfe = 0\n\n    for step_idx, i in enumerate(indices):\n        s = ts[i]; t_next = ts[i + 1]\n        x0_hat = denoiser(x, s * ones)\n        if mask is not None:\n            x0_hat = x0_hat * mask + x_T * (1 - mask)\n        a_s, b_s, c_s = [append_dims(v, x.ndim) for v in ns.get_abc(s * ones)]\n        a_t, b_t, c_t = [append_dims(v, x.ndim) for v in ns.get_abc(t_next * ones)]\n        z_hat = (x - b_s * x0_hat - a_s * x_T) / c_s\n        if step_idx < n_steps - 1:\n            progress = step_idx / max(n_steps - 1, 1)\n            eta_i = eta_max * (1.0 - progress) ** 2\n        else:\n            eta_i = 0.0\n        fresh_noise = generator.randn_like(x)\n        preserved_scale = c_t * ((1.0 - eta_i ** 2) ** 0.5)\n        fresh_scale = c_t * eta_i\n        x = b_t * x0_hat + a_t * x_T + preserved_scale * z_hat + fresh_scale * fresh_noise\n        if mask is not None:\n            x = x * mask + x_T * (1 - mask)\n        path.append(x.detach().cpu())\n        pred_x0.append(x0_hat.detach().cpu())\n        nfe += 1\n\n    return x, path, nfe, pred_x0, ts, first_noise\n'

OPS = [
    {
        "op": "replace",
        "file": "dbim-codebase/ddbm/karras_diffusion.py",
        "start_line": 448,
        "end_line": 463,
        "content": _BODY,
    },
]
