_BODY = '@torch.no_grad()\ndef sample_dbim(\n    denoiser,\n    diffusion,\n    x,\n    ts,\n    eta=1.0,\n    mask=None,\n    seed=None,\n    **kwargs,\n):\n    x_T = x\n    path = []\n    pred_x0 = []\n    ones = x.new_ones([x.shape[0]])\n    original_nfe = len(ts) - 1\n\n    t_max = float(diffusion.t_max)\n    t_min = float(diffusion.t_min)\n    rho_k = 0.6\n    sigma_min_ecsi = 0.15\n    sigma_max_offset = 5e-4\n    n_steps = len(ts)\n\n    t_lo = sigma_min_ecsi\n    t_hi = t_max - sigma_max_offset\n    min_inv_rho = t_lo ** (1.0 / rho_k)\n    max_inv_rho = t_hi ** (1.0 / rho_k)\n    ramp = torch.linspace(0.0, 1.0, n_steps, device=x.device, dtype=torch.float64)\n    ts_k = (max_inv_rho + ramp * (min_inv_rho - max_inv_rho)) ** rho_k\n    ts_new = torch.cat([ts_k, torch.tensor([t_min], device=x.device, dtype=ts_k.dtype)])\n\n    generator = BatchedSeedGenerator(seed)\n    first_noise = generator.randn_like(x)\n    path.append(x.detach().cpu())\n\n    x0_prev = None\n    t_prev = None\n\n    for _, i in enumerate(range(len(ts_new) - 1)):\n        s = ts_new[i]\n        t = ts_new[i + 1]\n\n        x0_hat = denoiser(x, s * ones)\n        if mask is not None:\n            x0_hat = x0_hat * mask + x_T * (1 - mask)\n\n        if x0_prev is not None:\n            r = float((s - t) / (t_prev - s))\n            x0_eff = x0_hat + 0.5 * r * (x0_hat - x0_prev)\n        else:\n            x0_eff = x0_hat\n\n        x0_prev = x0_hat\n        t_prev = s\n\n        a_s, b_s, c_s = [append_dims(item, x0_hat.ndim) for item in diffusion.noise_schedule.get_abc(s * ones)]\n        a_t, b_t, c_t = [append_dims(item, x0_hat.ndim) for item in diffusion.noise_schedule.get_abc(t * ones)]\n\n        _, _, rho_s, _ = [append_dims(item, x0_hat.ndim) for item in diffusion.noise_schedule.get_alpha_rho(s * ones)]\n        alpha_t, _, rho_t, _ = [\n            append_dims(item, x0_hat.ndim) for item in diffusion.noise_schedule.get_alpha_rho(t * ones)\n        ]\n\n        omega_st = eta * (alpha_t * rho_t) * (1 - rho_t**2 / rho_s**2).sqrt()\n        tmp_var = (c_t**2 - omega_st**2).sqrt() / c_s\n        coeff_xs = tmp_var\n        coeff_x0_hat = b_t - tmp_var * b_s\n        coeff_xT = a_t - tmp_var * a_s\n\n        noise = generator.randn_like(x0_hat)\n        x = coeff_x0_hat * x0_eff + coeff_xT * x_T + coeff_xs * x + (1 if i != len(ts_new) - 2 else 0) * omega_st * noise\n\n        path.append(x.detach().cpu())\n        pred_x0.append(x0_hat.detach().cpu())\n\n    return x, path, original_nfe, pred_x0, ts, first_noise\n'

OPS = [
    {
        "op": "replace",
        "file": "dbim-codebase/ddbm/karras_diffusion.py",
        "start_line": 448,
        "end_line": 463,
        "content": _BODY,
    },
]
